version: "3"  
services:
  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    networks: 
      - poll-tier
    environment: 
      - 0.0.0.0
    links: 
      - db
      - redis
    depends_on: 
      - redis
  redis:
    image: redis
    restart: always
    ports: 
      - "6379"
    networks: 
      - poll-tier
      - back-tier
  worker:
    build: ./worker
    restart: always
    image: worker
    networks: 
      - back-tier
    environment: 
      - 0.0.0.0
    depends_on: 
      - db
      - redis
  db:
    image: postgres:13.0
    restart: always
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    networks: 
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
  result:
    build: ./result
    restart: always
    image: result
    ports: 
      - "5001:80"
    networks: 
      - result-tier
    environment: 
      - 0.0.0.0
    depends_on: 
      - db
networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data: